In [55]:
import pandas as pd
df_games = pd.read_csv("../data/processed/games.csv")

df_games.head(10)

,game_id,season,game_type,game_date,game_state,home_team,home_score,away_team,away_score
0,2023020031,20232024,2,2023-10-14,OFF,VGK,4.0,ANA,1.0
1,2023020034,20232024,2,2023-10-15,OFF,ANA,6.0,CAR,3.0
2,2023020059,20232024,2,2023-10-19,OFF,ANA,2.0,DAL,3.0
3,2023020066,20232024,2,2023-10-21,OFF,ARI,2.0,ANA,1.0
4,2023020081,20232024,2,2023-10-22,OFF,ANA,1.0,BOS,3.0
5,2023020084,20232024,2,2023-10-24,OFF,CBJ,2.0,ANA,3.0
6,2023020100,20232024,2,2023-10-26,OFF,BOS,3.0,ANA,4.0
7,2023020117,20232024,2,2023-10-28,OFF,PHI,4.0,ANA,7.0
8,2023020132,20232024,2,2023-10-30,OFF,PIT,3.0,ANA,4.0
9,2023020144,20232024,2,2023-11-01,OFF,ANA,4.0,ARI,3.0

In [56]:
print("shape (rows, columns):", df_games.shape, "\n")

df_games.info()

shape (rows, columns): (3936, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3936 entries, 0 to 3935
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   game_id     3936 non-null   int64
 1   season      3936 non-null   int64
 2   game_type   3936 non-null   int64
 3   game_date   3936 non-null   object
 4   game_state  3936 non-null   object
 5   home_team   3936 non-null   object
 6   home_score  3936 non-null   float64
 7   away_team   3936 non-null   object
 8   away_score  3936 non-null   float64
dtypes: float64(2), int64(3), object(4)
memory usage: 276.9+ KB

In [57]:
team_games = pd.concat([df_games["home_team"], df_games["away_team"]]).value_counts()
team_games

VGK    246
ANA    246
CBJ    246
BOS    246
PHI    246
NSH    246
PIT    246
COL    246
EDM    246
NYR    246
VAN    246
CHI    246
NYI    246
DET    246
NJD    246
CAR    246
TBL    246
TOR    246
FLA    246
WSH    246
SJS    246
DAL    246
MIN    246
MTL    246
OTT    246
STL    246
BUF    246
LAK    246
WPG    246
CGY    246
SEA    246
UTA    164
ARI     82
Name: count, dtype: int64

In [58]:
df_games["home_win"] = df_games["home_score"] > df_games["away_score"]
df_games["home_win"].mean()

np.float64(0.541920731707317)

In [59]:
for i, column in enumerate(df_games.columns, start=1):
    print(f"\n column {i}------ {column} ------")
    print (df_games[column].unique())

 column 1------ game_id ------
[2023020031 2023020034 2023020059 ... 2025021290 2025020367 2025020503]

 column 2------ season ------
[20232024 20242025 20252026]

 column 3------ game_type ------
[2]

 column 4------ game_date ------
['2023-10-14' '2023-10-15' '2023-10-19' '2023-10-21' '2023-10-22'
 '2023-10-24' '2023-10-26' '2023-10-28' '2023-10-30' '2023-11-01'
 '2023-11-05' '2023-11-07' '2023-11-10' '2023-11-12' '2023-11-14'
 '2023-11-15' '2023-11-17' '2023-11-19' '2023-11-22' '2023-11-24'
 '2023-11-26' '2023-11-28' '2023-11-30' '2023-12-02' '2023-12-05'
 '2023-12-07' '2023-12-10' '2023-12-13' '2023-12-15' '2023-12-17'
 '2023-12-18' '2023-12-21' '2023-12-23' '2023-12-27' '2023-12-29'
 '2023-12-31' '2024-01-03' '2024-01-05' '2024-01-07' '2024-01-09'
 '2024-01-11' '2024-01-13' '2024-01-15' '2024-01-16' '2024-01-20'
 '2024-01-21' '2024-01-23' '2024-01-25' '2024-01-27' '2024-01-31'
 '2024-02-09' '2024-02-13' '2024-02-15' '2024-02-17' '2024-02-19'
 '2024-02-21' '2024-02-24' '2024-02-25' '2024-02-29' '2024-03-01'
 '2024-03-03' '2024-03-06' '2024-03-08' '2024-03-10' '2024-03-12'
 '2024-03-14' '2024-03-15' '2024-03-17' '2024-03-19' '2024-03-21'
 '2024-03-24' '2024-03-26' '2024-03-28' '2024-03-30' '2024-03-31'
 '2024-04-02' '2024-04-05' '2024-04-07' '2024-04-09' '2024-04-12'
 '2024-04-13' '2024-04-18' '2023-10-13' '2023-10-16' '2023-10-17'
 '2023-10-27' '2023-11-02' '2023-11-04' '2023-11-09' '2023-11-11'
 '2023-11-16' '2023-11-18' '2023-11-20' '2023-11-25' '2023-12-04'
 '2023-12-09' '2023-12-11' '2023-12-12' '2023-12-16' '2023-12-19'
 '2024-01-02' '2024-01-04' '2024-01-18' '2024-01-22' '2024-01-24'
 '2024-02-08' '2024-02-10' '2024-02-12' '2024-02-14' '2024-02-16'
 '2024-02-18' '2024-02-27' '2024-03-05' '2024-03-07' '2024-03-16'
 '2024-03-20' '2024-03-22' '2024-04-03' '2024-04-10' '2024-04-14'
 '2024-04-17' '2023-10-11' '2023-11-06' '2023-11-27' '2023-12-03'
 '2023-12-22' '2023-12-30' '2024-01-06' '2024-01-08' '2024-02-06'
 '2024-02-22' '2024-02-26' '2024-03-02' '2024-03-04' '2024-03-09'
 '2024-03-11' '2024-03-23' '2024-03-27' '2024-04-04' '2024-04-06'
 '2024-04-15' '2024-04-16' '2023-10-12' '2023-10-23' '2023-10-29'
 '2023-11-03' '2024-02-23' '2024-03-18' '2024-03-29' '2024-04-11'
 '2023-12-06' '2023-12-14' '2023-12-28' '2024-01-19' '2023-10-20'
 '2023-11-29' '2023-12-01' '2023-12-08' '2024-01-28' '2024-01-30'
 '2024-02-20' '2024-02-28' '2024-04-01' '2023-10-10' '2024-02-07'
 '2023-11-13' '2024-01-10' '2024-01-26' '2024-02-05' '2024-03-13'
 '2024-01-12' '2023-10-18' '2023-12-20' '2024-01-14' '2024-01-17'
 '2023-11-08' '2023-10-31' '2024-03-25' '2024-02-11' '2023-10-25'
 '2024-01-29' '2024-04-08' '2024-01-01' '2024-10-12' '2024-10-13'
 '2024-10-16' '2024-10-18' '2024-10-20' '2024-10-22' '2024-10-26'
 '2024-10-27' '2024-10-29' '2024-10-31' '2024-11-03' '2024-11-05'
 '2024-11-08' '2024-11-10' '2024-11-13' '2024-11-15' '2024-11-18'
 '2024-11-19' '2024-11-22' '2024-11-25' '2024-11-27' '2024-11-29'
 '2024-12-01' '2024-12-04' '2024-12-06' '2024-12-09' '2024-12-11'
 '2024-12-12' '2024-12-14' '2024-12-18' '2024-12-20' '2024-12-22'
 '2024-12-23' '2024-12-28' '2024-12-29' '2024-12-31' '2025-01-02'
 '2025-01-03' '2025-01-05' '2025-01-07' '2025-01-09' '2025-01-11'
 '2025-01-12' '2025-01-14' '2025-01-16' '2025-01-18' '2025-01-21'
 '2025-01-23' '2025-01-25' '2025-01-28' '2025-01-30' '2025-02-02'
 '2025-02-04' '2025-02-08' '2025-02-22' '2025-02-23' '2025-02-25'
 '2025-02-27' '2025-03-01' '2025-03-04' '2025-03-05' '2025-03-07'
 '2025-03-09' '2025-03-11' '2025-03-12' '2025-03-14' '2025-03-16'
 '2025-03-18' '2025-03-20' '2025-03-23' '2025-03-26' '2025-03-28'
 '2025-03-30' '2025-04-01' '2025-04-03' '2025-04-05' '2025-04-07'
 '2025-04-09' '2025-04-10' '2025-04-13' '2025-04-15' '2025-04-16'
 '2024-10-08' '2024-10-10' '2024-10-14' '2024-10-19' '2024-10-24'
 '2024-11-02' '2024-11-07' '2024-11-09' '2024-11-12' '2024-11-14'
 '2024-11-16' '2024-11-21' '2024-11-23' '2024-11-26' '2024-12-03'
 '2024-12-07' '2024-12-10' '2024-12-17' '2024-12-19' '2024-12-21'
 '2024-12-27' '2025-01-04' '2025-01-20' '2025-01-22' '2025-02-01'
 '2025-02-05' '2025-03-02' '2025-03-06' '2025-03-08' '2025-03-13'
 '2025-03-15' '2025-03-17' '2025-03-22' '2025-03-29' '2025-04-06'
 '2025-04-08' '2024-10-04' '2024-10-05' '2024-10-17' '2024-10-28'
 '2024-11-01' '2024-11-11' '2024-11-20' '2024-11-30' '2024-12-05'
 '2024-12-15' '2025-01-06' '2025-01-15' '2025-01-17' '2025-01-31'
 '2025-03-03' '2025-03-10' '2025-03-25' '2025-03-27' '2025-04-12'
 '2025-04-17' '2024-10-11' '2024-10-15' '2024-11-17' '2024-12-13'
 '2025-01-10' '2025-02-06' '2025-04-02' '2025-04-04' '2024-10-30'
 '2024-12-08' '2025-03-21' '2025-03-24' '2024-10-09' '2025-01-13'
 '2025-01-26' '2025-03-31' '2025-04-11' '2024-10-25' '2024-11-06'
 '2024-12-02' '2025-01-08' '2025-01-24' '2025-02-07' '2025-04-14'
 '2024-12-16' '2025-02-26' '2025-02-28' '2025-03-19' '2025-01-19'
 '2025-01-27' '2024-11-04' '2024-12-30' '2025-01-29' '2025-01-01'
 '2025-02-24' '2025-02-09' '2025-02-03' '2024-10-23' '2024-10-21'
 '2024-11-24' '2025-10-09' '2025-10-11' '2025-10-14' '2025-10-16'
 '2025-10-19' '2025-10-21' '2025-10-23' '2025-10-25' '2025-10-28'
 '2025-10-31' '2025-11-02' '2025-11-04' '2025-11-06' '2025-11-08'
 '2025-11-09' '2025-11-11' '2025-11-13' '2025-11-15' '2025-11-17'
 '2025-11-19' '2025-11-20' '2025-11-22' '2025-11-26' '2025-11-28'
 '2025-11-30' '2025-12-01' '2025-12-03' '2025-12-05' '2025-12-07'
 '2025-12-09' '2025-12-11' '2025-12-13' '2025-12-15' '2025-12-16'
 '2025-12-19' '2025-12-20' '2025-12-22' '2025-12-27' '2025-12-29'
 '2025-12-31' '2026-01-02' '2026-01-05' '2026-01-06' '2026-01-08'
 '2026-01-10' '2026-01-13' '2026-01-16' '2026-01-17' '2026-01-19'
 '2026-01-21' '2026-01-23' '2026-01-25' '2026-01-26' '2026-01-29'
 '2026-02-01' '2026-02-03' '2026-02-25' '2026-02-27' '2026-03-01'
 '2026-03-03' '2026-03-04' '2026-03-06' '2026-03-08' '2026-03-10'
 '2026-03-12' '2026-03-14' '2026-03-15' '2026-03-18' '2026-03-20'
 '2026-03-22' '2026-03-24' '2026-03-26' '2026-03-28' '2026-03-30'
 '2026-04-01' '2026-04-03' '2026-04-04' '2026-04-07' '2026-04-09'
 '2026-04-12' '2026-04-14' '2026-04-16' '2025-10-08' '2025-10-13'
 '2025-10-18' '2025-10-27' '2025-10-30' '2025-11-01' '2025-11-21'
 '2025-11-23' '2025-11-29' '2025-12-02' '2025-12-04' '2025-12-06'
 '2025-12-14' '2025-12-18' '2025-12-21' '2025-12-23' '2026-01-03'
 '2026-01-11' '2026-01-15' '2026-01-20' '2026-01-22' '2026-01-24'
 '2026-01-27' '2026-02-04' '2026-02-26' '2026-02-28' '2026-03-05'
 '2026-03-07' '2026-03-16' '2026-03-17' '2026-03-19' '2026-03-21'
 '2026-03-25' '2026-03-29' '2026-03-31' '2026-04-02' '2026-04-05'
 '2026-04-11' '2025-10-15' '2025-10-20' '2025-10-22' '2025-10-24'
 '2025-11-12' '2025-12-08' '2026-01-12' '2026-01-14' '2026-01-31'
 '2026-02-02' '2026-02-05' '2026-03-27' '2026-04-06' '2026-04-08'
 '2026-04-13' '2026-04-15' '2025-11-14' '2025-12-17' '2025-12-30'
 '2026-01-01' '2026-01-04' '2026-03-02' '2025-10-29' '2025-11-05'
 '2025-11-10' '2025-11-18' '2025-11-24' '2025-12-28' '2026-01-28'
 '2026-01-30' '2026-03-09' '2025-10-26' '2025-11-07' '2025-12-10'
 '2026-01-07' '2025-10-07' '2025-10-17' '2025-11-03' '2025-12-12'
 '2026-01-09' '2025-11-16' '2025-11-25' '2026-01-18' '2026-03-13'
 '2026-03-11' '2025-10-12' '2026-03-23']

 column 5------ game_state ------
['OFF']

 column 6------ home_team ------
['VGK' 'ANA' 'ARI' 'CBJ' 'BOS' 'PHI' 'PIT' 'NSH' 'COL' 'EDM' 'VAN' 'CHI'
 'NYI' 'NYR' 'NJD' 'DET' 'CAR' 'TBL' 'FLA' 'WSH' 'SJS' 'DAL' 'MIN' 'MTL'
 'OTT' 'TOR' 'BUF' 'LAK' 'WPG' 'STL' 'SEA' 'CGY' 'UTA']

 column 7------ home_score ------
[ 4.  6.  2.  1.  3.  0.  8.  5.  9.  7. 10.]

 column 8------ away_team ------
['ANA' 'CAR' 'DAL' 'BOS' 'ARI' 'VGK' 'PIT' 'PHI' 'SJS' 'FLA' 'STL' 'MTL'
 'LAK' 'WSH' 'COL' 'WPG' 'CGY' 'SEA' 'EDM' 'TOR' 'DET' 'NYR' 'BUF' 'CBJ'
 'NSH' 'NJD' 'VAN' 'OTT' 'NYI' 'MIN' 'CHI' 'TBL' 'UTA']

 column 9------ away_score ------
[ 1.  3.  4.  7.  2.  6.  5.  0.  8.  9. 10.]

 column 10------ home_win ------
[ True False]

In [60]:
df_games.describe(include="all")

,game_id,season,game_type,game_date,game_state,home_team,home_score,away_team,away_score,home_win
count,3.936000e+03,3.936000e+03,3936.0,3936,3936,3936,3936.000000,3936,3936.000000,3936
unique,NaN,NaN,NaN,528,1,33,NaN,33,NaN,2
top,NaN,NaN,NaN,2024-01-13,OFF,VGK,NaN,ANA,NaN,True
freq,NaN,NaN,NaN,16,3936,123,NaN,123,NaN,2133
mean,2.024021e+09,2.024202e+07,2.0,NaN,NaN,NaN,3.207317,NaN,2.979421,NaN
std,8.166004e+05,8.166820e+03,0.0,NaN,NaN,NaN,1.762148,NaN,1.726344,NaN
min,2.023020e+09,2.023202e+07,2.0,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN
25%,2.023021e+09,2.023202e+07,2.0,NaN,NaN,NaN,2.000000,NaN,2.000000,NaN
50%,2.024021e+09,2.024202e+07,2.0,NaN,NaN,NaN,3.000000,NaN,3.000000,NaN
75%,2.025020e+09,2.025203e+07,2.0,NaN,NaN,NaN,4.000000,NaN,4.000000,NaN
max,2.025021e+09,2.025203e+07,2.0,NaN,NaN,NaN,10.000000,NaN,10.000000,NaN

IMPORTANT REMINDER: game_type is always 2 because we defined it like that in the ingestion process. Why?:

1 -> Preseason

2 -> Regular Season

3 -> Playoffs